---
title: "titanic : 타이타닉호의 생존자 예측"
author: "고은미"
date: '2020 1 6 '
output: html_document
---
출처 : 캐글(Kaggle)

#라이브러리 및 원본데이터 설치
```{r}
install.packages(c("rpart", "rpart.plot", "ggplot2"))
library(rpart)
library(rpart.plot)
library(ggplot2)

train <- read.csv("titanic_train.csv")
test <- read.csv("titanic_test.csv")
```

# 개별 속성 분석
```{r}
# 1. 데이터 전체 분포 관찰 : 속성별 값의 분포 확인
summary(train)

# 2. 예측 목표가 되는 생존 여부의 분포 확인 : 38% 승객 생존
table(train$Survived)

# 3. 확률 분포 : 티켓가격-나이
# 티켓가격 : 50불 미만이 대부분, 나이 : 20~40대층과 그들의 자녀일 수있는 어린아이가 많음
par(mfrow=c(1,2))
plot(density(train$Fare), main="", xlab="Fare Distribution")
plot(density(train[!is.na(train$Age),]$Age), main="", xlab="Age Distribution")
```

# 속성간 관계 분석
```{r, fig.width=8, fig.height=8, warning=FALSE}
par(mfrow=c(3,2))

# 남/녀 생존률 비교 : 남성 사망률이 높음
mosaicplot(table(ifelse(train$Survived==1, "Survived", "Dead"), train$Sex), main="남/녀 생존률 비교", cex=1.2)
# 각 객실별 생존률 비교 : 3등석 손님의 사망률이 높음
mosaicplot(table(ifelse(train$Survived==1, "Survived", "Dead"), train$Pclass), main="객실별 생존률 비교", cex=1.2)

# 나이와 생존여부 관계 확인1 : 생존자의 나이가 약간 어리고, 두 그룹간 차이가 없음
boxplot(Age~ifelse(Survived==1, "Survived", "Dead"), train, xlab="Survival", ylab="Age", cex=1.2, main="생존여부별 나이분포1")
# 확인2 : 생존자중 아이의 비율이 높음 / 사망자중 20대,노인의 비율이 높음 
plot(Age~jitter(Survived), train, cex=1.2, xlab="Survival", main="생존여부별 나이분포2")

# 나이/성별별 티켓가격 분포도
qplot(jitter(Age), jitter(log(Fare)), data=train, color=factor(Survived), shape=factor(Sex))
```

# 예측 모델 설정 : 의사결정 트리
```{r}
fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data=train, method="class")
rpart.plot(fit)
```

# 실험데이터에 모델 적용 

```{r}
Prediction <- predict(fit, test, type="class")
submit <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)
write.csv(submit, file="titanic_submission.tsv", row.names=FALSE)
```

